### ISSUE TITLE
data file p7zip-binary-64bit.zip can't be downloaded

### ISSUE THREAD

**Issue by amiltonwong** [nsavinov/semantic3dnet#1]
Hi, @nsavinov ,

According to  the line [12](https://github.com/nsavinov/semantic3dnet/blob/master/build/setup.sh#L12) in setup.sh, p7zip-binary-64bit.zip is needed to download. However, the download link "https://dl.dropboxusercontent.com/u/7069946/p7zip-binary-64bit.zip" is broken now, pls help to fix it!

THX~

**Comment by nsavinov** [comment]
Hi @amiltonwong ,
Thanks for letting me know! This should be fixed now.
