### ISSUE TITLE
message from ./build_run.sh

### ISSUE THREAD

**Issue by amiltonwong** [nsavinov/semantic3dnet#2]
Hi, @nsavinov ,

When I run './build_run.sh' , I got the following message. Does it matter?

```
root@milton-OptiPlex-9010:/data/code/semantic3dnet/build# ./build_run.sh 
-- compilation flags: 
-- Configuring done
-- Generating done
-- Build files have been written to: /data/code/semantic3dnet/build
[ 71%] Built target pointCloudUtil
[100%] Built target point_cloud_main
tcmalloc: large alloc 1610612736 bytes == 0x63018000 @  0x7fa551568c4c 0x7fa551588989 0x7fa55135249b 0x7fa55134f95c 0x7fa55134f9e5 0x7fa55135069a 0x7fa551350965 0x7fa551350aa0 0x7fa551350ade 0x7fa551350c80 0x400bf8 0x7fa550a7cf45 0x400d5a (nil)

```

**Comment by nsavinov** [comment]
Hi, @amiltonwong ,

Please take a look here: https://www.novell.com/support/kb/doc.php?id=7012805
Apparently, it allocated 1.6Gb, which is not much for this task (note that I've put the requirement 8Gb RAM for the code in this repository, make sure you have at least this amount available).
