### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by amiltonwong** [nsavinov/semantic3dnet#3]
Hi, @nsavinov ,

After I run ./launch_train.sh, which in fact run the train_point_cloud.lua, I got the following error:

```
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/cudnn/convert.lua:64: attempt to call method 'replace' (a nil value)
stack traceback:
	/root/torch/install/share/lua/5.1/cudnn/convert.lua:64: in function 'convert'
	train_point_cloud.lua:43: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
```

Detailed [log file](https://gist.github.com/amiltonwong/797bfc3e3f400593bfd8074db87dd8c6)

Any suggestion to fix this problem?

THX!

**Comment by nsavinov** [comment]
Hi, @amiltonwong ,

Did you run the code with exactly the same setup as it was tested with? Please refer to the instructions in the documentation page for the torch commit version and cudnn version.

**Comment by nsavinov** [comment]
@amiltonwong It should have worked with the torch commit version mentioned in readme. Anyway, I made it work with the latest version of torch as well (and updated the readme). Your issue should be resolved now.
