### ISSUE TITLE
No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by '../python/Semantic3D.so'.  Stop.

### ISSUE THREAD

**Issue by ChidanandKumarKS** [nsavinov/semantic3dnet#4]
I got the error below while building this library

[ 50%] Building CXX object src/CMakeFiles/Semantic3D.dir/Sem3D.cxx.o
<command-line>:0:15: warning: missing whitespace after the macro name
[ 66%] Building CXX object src/CMakeFiles/Semantic3D.dir/pointCloudLabels.cxx.o
<command-line>:0:15: warning: missing whitespace after the macro name
[ 83%] Building CXX object src/CMakeFiles/Semantic3D.dir/pointCloud.cxx.o
<command-line>:0:15: warning: missing whitespace after the macro name
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libproj.so', needed by '../python/Semantic3D.so'.  Stop.
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/Semantic3D.dir/all' failed
make[1]: *** [src/CMakeFiles/Semantic3D.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Kindly provide the solution

**Comment by nsavinov** [comment]
I don't have such paths in my code: src/CMakeFiles/Semantic3D.dir/Sem3D.cxx.o . What are running, exactly?
You might want to follow the instructions I provided in the documentation.

**Comment by nsavinov** [comment]
I'm going to close this for now.
